CREATE TABLE BARCOS
(
MATRICULA VARCHAR2(10),
NOMBRE VARCHAR2(25),
CLASE VARCHAR2(10),
ARMADOR VARCHAR2(10),
CAPACIDAD NUMBER,
NACIONALIDAD VARCHAR2(10)
);


CREATE TABLE ESPECIE 
(
CODIGO VARCHAR2(10),
NOMBRE VARCHAR2(25),
TIPO VARCHAR2(10),
CUPO_POR_BARCO NUMBER,
CALDERO_PRINCIPAL VARCHAR2(10)
);


CREATE TABLE CALDERO 
(
CODIGO VARCHAR2(10),
NOMBRE VARCHAR2(25),
UBICACION VARCHAR2(10),
ESPECIE_PRINCIPAL VARCHAR2(10)
);


CREATE TABLE LOTES 
(
CODIGO VARCHAR2(10),
MATRICULA VARCHAR2(10),
NUM_KILOS NUMBER,
PRECIO_POR_KILO_SALIDA NUMBER,
PRECIO_POR_KILO_ADJUDICADO NUMBER,
FECHA_VENTA DATE,
COD_ESPECIE VARCHAR2(10)
);


CREATE TABLE FECHAS_CAPTURAS_PERMITIDAS 
(
COD_ESPECIE VARCHAR2(10),
COD_CALDERO VARCHAR2(10),
FECHA_INICIAL DATE,
FECHA_FINAL DATE
);



ALTER TABLE BARCOS ADD CONSTRAINT PK_BARCOS PRIMARY KEY(MATRICULA);
ALTER TABLE BARCOS ADD CONSTRAINT CHK_CAPACIDAD_POSITIVA CHECK (CAPACIDAD > 0);

ALTER TABLE ESPECIE ADD CONSTRAINT PK_ESPECIE PRIMARY KEY(CODIGO);
ALTER TABLE ESPECIE ADD CONSTRAINT CHK_CUPO_POSITIVO CHECK (CUPO_POR_BARCO > 0);

ALTER TABLE CALDERO ADD CONSTRAINT PK_CALDERO PRIMARY KEY(CODIGO);
ALTER TABLE CALDERO ADD CONSTRAINT FK_CALDERO FOREIGN KEY(ESPECIE_PRINCIPAL) REFERENCES ESPECIE(CODIGO) ON DELETE SET NULL;
ALTER TABLE CALDERO ADD CONSTRAINT CHK_NOMBRE_NO_NULO CHECK (NOMBRE IS NOT NULL);

ALTER TABLE ESPECIE ADD CONSTRAINT FK_ESPECIE FOREIGN KEY(CALDERO_PRINCIPAL) REFERENCES CALDERO(CODIGO);

ALTER TABLE LOTES ADD CONSTRAINT PK_LOTES PRIMARY KEY(CODIGO);
ALTER TABLE LOTES ADD CONSTRAINT FK1_LOTES FOREIGN KEY(MATRICULA) REFERENCES BARCOS(MATRICULA) ON DELETE CASCADE;
ALTER TABLE LOTES ADD CONSTRAINT FK2_LOTES FOREIGN KEY(COD_ESPECIE) REFERENCES ESPECIE(CODIGO) ON DELETE CASCADE;
ALTER TABLE LOTES ADD CONSTRAINT CHK_PRECIO_POSITIVO CHECK (PRECIO_POR_KILO_SALIDA > 0 AND PRECIO_POR_KILO_ADJUDICADO > 0);



ALTER TABLE FECHAS_CAPTURAS_PERMITIDAS ADD CONSTRAINT PK_FECHAS_CAPTURAS_PERMITIDAS PRIMARY KEY(COD_ESPECIE,COD_CALDERO);
ALTER TABLE FECHAS_CAPTURAS_PERMITIDAS ADD CONSTRAINT FK1_FECHAS_CAPTURAS_PERMITIDAS FOREIGN KEY(COD_ESPECIE) REFERENCES ESPECIE(CODIGO);
ALTER TABLE FECHAS_CAPTURAS_PERMITIDAS ADD CONSTRAINT CHK_FECHA_FINAL_MAYOR CHECK (FECHA_FINAL > FECHA_INICIAL);























