
CREATE TABLE CLIENTE
(
NIF VARCHAR2(10),
NOMBRE VARCHAR2(25),
DIRECCION VARCHAR2(40),
TELEFONO VARCHAR2(10),
CONSTRAINT PK_CLIENTE PRIMARY KEY(NIF)
);

CREATE TABLE MODELODORMITORIO
(
COD VARCHAR2(20),
CONSTRAINT PK_MODELODORMITORIO PRIMARY KEY(COD)
);

CREATE TABLE MONTADOR
(
NIF VARCHAR2(20),
NOMBRE VARCHAR2(25),
DIRECCION VARCHAR2(40),
TELEFONO VARCHAR2(10),
CONSTRAINT PK_MONTADOR PRIMARY KEY(NIF)
);

CREATE TABLE COMPRA
(
NIF_C VARCHAR2(10),
MODELO VARCHAR2(20),
FECHACOMPRA DATE,
CONSTRAINT PK_COMPRA PRIMARY KEY(FECHACOMPRA,MODELO,NIF_C),
CONSTRAINT FK1_COMPRA FOREIGN KEY(NIF_C) REFERENCES CLIENTE(NIF),
CONSTRAINT FK2_COMPRA FOREIGN KEY(MODELO) REFERENCES MODELODORMITORIO(COD)
);

CREATE TABLE MONTA
(
MODELO VARCHAR2(20),
NIF_M VARCHAR(20),
FECHAMONTAJE DATE,
CONSTRAINT PK_MONTA PRIMARY KEY(FECHAMONTAJE,MODELO,NIF_M),
CONSTRAINT FK1_MONTA FOREIGN KEY(MODELO) REFERENCES MODELODORMITORIO(COD),
CONSTRAINT FK2_MONTA FOREIGN KEY(NIF_M) REFERENCES MONTADOR(NIF)
);
