CREATE TABLE CLIENTE
(
CODCLIENTE VARCHAR2(25),
DNI VARCHAR2(10) UNIQUE,
NOMBRE VARCHAR2(25) NOT NULL,
DIRECCION VARCHAR2(40),
TELEFENO VARCHAR2(10),
CONSTRAINT PK_CLIENTE PRIMARY KEY(CODCLIENTE)
);

CREATE TABLE AVALA 
(
AVALADO VARCHAR2(10),
AVALADOR VARCHAR2(10),
CONSTRAINT PK_AVALA PRIMARY KEY(AVALADO),
CONSTRAINT FK1_AVALA FOREIGN KEY(AVALADO) REFERENCES CLIENTE(CODCLIENTE),
CONSTRAINT FK2_AVALA FOREIGN KEY(AVALADOR) REFERENCES CLIENTE(CODCLIENTE)
);

CREATE TABLE RESERVA 
(
NUMERO VARCHAR2(10),
FECHAINICIO DATE,
FECHAFIN DATE,
PRECIOTOTAL NUMBER(10),
CODCLIENTE VARCHAR2(25),
CONSTRAINT PK_RESERVA PRIMARY KEY(NUMERO),
CONSTRAINT FK1_RESERVA FOREIGN KEY(CODCLIENTE) REFERENCES CLIENTE(CODCLIENTE)
);

CREATE TABLE COCHE
(
MATRICULA NUMBER(10),
MARCA VARCHAR2(10) NOT NULL,
MODELO VARCHAR2(20) NOT NULL,
COLOR VARCHAR2(15),
PRECIOHORA VARCHAR(25),
CONSTRAINT PK_COCHE PRIMARY KEY(MATRICULA)
);
CREATE TABLE INCLUYE 
(
NUMERO VARCHAR2(10),
MATRICULA NUMBER(10),
LITROGAS VARCHAR2(15),
CONSTRAINT PK_INCLUYE PRIMARY KEY(NUMERO,MATRICULA),
CONSTRAINT FK1_INCLUYE FOREIGN KEY(NUMERO) REFERENCES RESERVA(NUMERO),
CONSTRAINT FK2_INCLUYE FOREIGN KEY(MATRICULA) REFERENCES COCHE(MATRICULA)
);