CREATE TABLE ARTICULO
(
NUM_ARTICULO VARCHAR2(20),
DESCRIPCION VARCHAR2(20)
);

CREATE TABLE FABRICA 
(
NUM_FABRICA VARCHAR(15),
TELEFONO VARCHAR2(10)
);

CREATE TABLE DIRECCION 
(
COD_DIRECCION VARCHAR2(15),
VIA VARCHAR2(15),
NOMBRE_VIA VARCHAR2(15),
NUMERO VARCHAR(5),
PISO VARCHAR2(5),
PORTAL VARCHAR2(5),
COD_POSTAL VARCHAR2(10)
);

CREATE TABLE DISTRIBUYE 
(
NUM_ARTICULO VARCHAR2(15),
NUM_FABRICA VARCHAR2(10),
CANT_SUMINISTRO VARCHAR2(10),
EXISTENCIAS VARCHAR2(10)
);

CREATE TABLE INCLUYE 
(
NUM_PEDIDO VARCHAR2(10),
NUM_ARTICULO VARCHAR2(10),
CANTIDAD VARCHAR2(10)
);

CREATE TABLE PEDIDO 
(
NUMJ_PEDIDO VARCHAR2(10),
FECHA DATE,
NUM_CLIENTE VARCHAR2(10),
COD_DIRECCION VARCHAR2(15)
);

CREATE TABLE CLIENTE 
(
NUM_CLIENTE VARCHAR2(10),
SALDO VARCHAR2(10),
LIM_CREDITO VARCHAR2(15),
DESCUENTO VARCHAR2(5)
);


CREATE TABLE POSEE 
(
NUM_CLIENTE VARCHAR2(10),
COD_DIRECCION VARCHAR2(15)
);



ALTER TABLE ARTICULO ADD CONSTRAINT PK_ARTICULO PRIMARY KEY(NUM_ARTICULO);

ALTER TABLE FABRICA ADD CONSTRAINT PK_FABRICA PRIMARY KEY(NUM_FABRICA);

ALTER TABLE DISTRIBUYE ADD CONSTRAINT PK_DISTRIBUYE PRIMARY KEY(NUM_ARTICULO,NUM_FABRICA);
ALTER TABLE DISTRIBUYE ADD CONSTRAINT FK1_DISTRIBUYE FOREIGN KEY(NUM_ARTICULO) REFERENCES ARTICULO(NUM_ARTICULO);
ALTER TABLE DISTRIBUYE ADD CONSTRAINT FK2_DISTRIBUYE FOREIGN KEY(NUM_FABRICA) REFERENCES FABRICA(NUM_FABRICA);

ALTER TABLE DIRECCION ADD CONSTRAINT PK_DIRECCION PRIMARY KEY(COD_DIRECCION);

ALTER TABLE PEDIDO ADD CONSTRAINT PK_PEDIDO PRIMARY KEY(NUM_PEDIDO);

ALTER TABLE INCLUYE ADD CONSTRAINT PK_INCLUYE PRIMARY KEY(NUM_PEDIDO,NUM_ARTICULO);
ALTER TABLE INCLUYE ADD CONSTRAINT FK1_INCLUYE FOREIGN KEY(NUM_PEDIDO) REFERENCES PEDIDO(NUM_PEDIDO);
ALTER TABLE INCLUYE ADD CONSTRAINT FK2_INCLUYE FOREIGN KEY(NUM_ARTICULO) REFERENCES ARTICULO(NUM_ARTICULO);

ALTER TABLE CLIENTE CONSTRAINT PK_CLIENTE PRIMARY KEY(NUM_CLIENTE);

ALTER TABLE POSEE ADD CONSTRAINT PK_POSEE PRIMARY KEY(NUM_CLIENTE,COD_DIRECCION);
ALTER TABLE POSEE ADD CONSTRAINT FK1_POSEE FOREIGN KEY(NUM_CLIENTE) REFERENCES CLIENTE(NUM_CLIENTE);
ALTER TABLE POSEE ADD CONSTRAINT FK2_POSEE FOREIGN KEY(COD_DIRECCION) REFERENCES DIRECCION(COD_DIRECCION);

























































