CREATE TABLE  PERIODISTA 
(
DNI VARCHAR2(10),
NOMBRE VARCHAR2(25) NOT NULL,
DIRECCION VARCHAR2(30),
TELEFONO VARCHAR2(10),
ESPECIALISTA VARCHAR2(10),
CONSTRAINT PK_PERIODISTA PRIMARY KEY(DNI)
);

CREATE TABLE SUCURSAL 
(
CODIGO VARCHAR2(30),
DIRECCION VARCHAR2(30),
TELEFONO VARCHAR2(10),
CONSTRAINT PK_SUCURSAL PRIMARY KEY(CODIGO)
);

CREATE TABLE REVISTA 
(
NUMREG VARCHAR2(10),
TITULO VARCHAR(20) NOT NULL,
PERIODICIDAD  VARCHAR2(20) DEFAULT 'MENSUAL',
TIPO VARCHAR2(20),
SUCURSAL VARCHAR2(25),
CONSTRAINT PK_REVISTA PRIMARY KEY(NUMREG),
CONSTRAINT FK1_REVISTA FOREIGN KEY(SUCURSAL) REFERENCES SUCURSAL(CODIGO)
);

CREATE TABLE ESCRIBE
(
NUMREG VARCHAR2(10),
DNI_PER VARCHAR2(10),
CONSTRAINT PK_ESCRIBE PRIMARY KEY(NUMREG,DNI_PER),
CONSTRAINT FK1_ESCRIBE FOREIGN KEY(NUMREG) REFERENCES REVISTA(NUMREG),
CONSTRAINT FK2_ESCRIBE FOREIGN KEY(DNI_PER) REFERENCES PERIODISTA(DNI)
);

CREATE TABLE NUMREVISTA 
(
NUMREG VARCHAR2(10),
NUMERO VARCHAR2(10),
NUMPAGINAS VARCHAR(100) DEFAULT 1,
FECHA DATE,
CANTVENDIDAS NUMBER(30),
CONSTRAINT PK_NUMREVISTA PRIMARY KEY(NUMREG,NUMERO),
CONSTRAINT FK1_NUMREVISTA FOREIGN KEY(NUMREG) REFERENCES REVISTA(NUMREG)
);

CREATE TABLE EMPLEADO 
(
DNI VARCHAR2(10),
NOMBRE VARCHAR2(25),
DIRECCION VARCHAR2(30),
TELEFONO VARCHAR2(10),
SUCURSAL VARCHAR2(25),
CONSTRAINT PK_EMPLEADO PRIMARY KEY(DNI),
CONSTRAINT FK1_EMPLEADO FOREIGN KEY(SUCURSAL) REFERENCES SUCURSAL(CODIGO)
);































