CREATE TABLE SUCURSAL 
(
COD_SUCURSAL VARCHAR2(10),
NOMBRE VARCHAR2(25),
DIRECCION VARCHAR2(20),
LOCALIDAD VARCHAR2(15)
);

CREATE TABLE CLIENTE 
(
DNI VARCHAR2(10),
NOMBRE VARCHAR2(25),
DIRECCION VARCHAR2(20),
LOCALIDAD VARCHAR2(15),
FECHA_NAC DATE,
SEXO VARCHAR2(5)
);

CREATE TABLE CUENTA 
(
COD_SUCURSAL VARCHAR2(10),
COD_CUENTA VARCHAR2(15)
);

CREATE TABLE TRANSACCION 
(
COD_SUCURSAL VARCHAR2(10),
COD_CUENTA VARCHAR2(10),
NUM_TRANSACCION VARCHAR2(15),
FECHA DATE,
CANTIDAD VARCHAR2(20),
TIPO VARCHAR2(10)
);

CREATE TABLE CLI_CUENTA
(
COD_SUCURSAL VARCHAR2(10),
COD_CUENTA VARCHAR2(10),
DNI VARCHAR2(10)
);


ALTER TABLE SUCURSAL
ADD PRIMARY KEY (COD_SUCURSAL);


ALTER TABLE CLIENTE 
ADD PRIMARY KEY (DNI);


ALTER TABLE CUENTA 
ADD PRIMARY KEY (COD_SUCURSAL,COD_CUENTA);
ADD FOREIGN KEY (COD_SUCURSAL);


ALTER TABLE TRANSACCION 
ADD PRIMARY KEY (COD_SUCURSAL,COD_CUENTA,NUM_TRANSACCION);
ADD FOREIGN KEY (COD_SUCURSAL,COD_CUENTA);


ALTER TABLE CLI_CUENTA
ADD PRIMARY KEY (COD_SUCURSAL,COD_CUENTA,DNI);
ADD FOREIGN KEY (COD_SUCURSAL,COD_CUENTA);
ADD FOREIGN KEY (DNI);

















