CREATE TABLE  DIRECTOR 
(
NOMBRE VARCHAR2(25),
NACIONALIDAD VARCHAR2(15),
CONSTRAINT PK_DIRECTOR PRIMARY KEY(NOMBRE)
);

CREATE TABLE PELICULA
(
ID VARCHAR2(20),
TITULO VARCHAR2(20) NOT NULL,
PRODUCTORA VARCHAR2(20),
NACIONALIDAD VARCHAR2(15),
FECHA DATE,
DIRECTOR VARCHAR2(15),
CONSTRAINT PK_PELICULA PRIMARY KEY(ID),
CONSTRAINT FK1_PELICULA FOREIGN KEY(DIRECTOR) REFERENCES DIRECTOR(NOMBRE)
);

CREATE TABLE ACTORES 
(
NOMBRE VARCHAR2(25),
NACIONALIDAD VARCHAR2(15),
SEXO VARCHAR2(2),
CONSTRAINT PK_ACTORES PRIMARY KEY(NOMBRE)
);

CREATE TABLE ACTUA 
(
ACTOR VARCHAR2(25) DEFAULT 'NO PROTAGONISTA',
ID_PELI VARCHAR2(30),
PROTA VARCHAR2(5) DEFAULT 'NO',
CONSTRAINT PK_ACTUA PRIMARY KEY(ACTOR,ID_PELI),
CONSTRAINT FK1_ACTUA FOREIGN KEY(ACTOR) REFERENCES ACTORES(NOMBRE),
CONSTRAINT FK2_ACTUA FOREIGN KEY(ID_PELI) REFERENCES PELICULA(ID)
);

CREATE TABLE EJEMPLAR 
(
ID_PELI VARCHAR2(30),
NUMERO VARCHAR2(20),
ESTADO VARCHAR2(10),
CONSTRAINT PK_EJEMPLAR PRIMARY KEY(ID_PELI,NUMERO),
CONSTRAINT FK1_EJEMPLAR FOREIGN KEY(ID_PELI) REFERENCES PELICULA(ID)
);

CREATE TABLE SOCIO 
(
DNI VARCHAR2(10),
NOMBRE VARCHAR2(25),
DIRECCION VARCHAR2(30),
TELEFONO NUMBER,
AVALADOR VARCHAR2(25),
CONSTRAINT PK_SOCIO PRIMARY KEY(DNI),
CONSTRAINT FK1_SOCIO FOREIGN KEY(AVALADOR) REFERENCES SOCIO(DNI)
);

CREATE TABLE ALQUILA 
(
DNI VARCHAR2(10),
ID_PELI VARCHAR2(30),
NUMERO NUMBER,
FECHA_ALQUILER VARCHAR2(20),
FECHA_DEVOLUCION VARCHAR2(20),
CONSTRAINT PK_ALQUILA PRIMARY KEY(DNI,ID_PELI,NUMERO,FECHA_ALQUILER),
CONSTRAINT FK1_ALQUILA FOREIGN KEY(DNI) REFERENCES SOCIO(DNI),
CONSTRAINT FK2_ALQUILA FOREIGN KEY(ID_PELI) REFERENCES EJEMPLAR(ID_PELI),
CONSTRAINT FK3_ALQUILA FOREIGN KEY(NUMERO) REFERENCES EJEMPLAR(NUMERO)
);



























