CREATE TABLE CATEGORIA 
(
ID_CATEGORIA VARCHAR2(10),
NOMBRE VARCHAR2(25),
DESCRIPCION VARCHAR2(30)
);

CREATE TABLE PROVEEDOR 
(
COD_PROVEEDOR VARCHAR(10),
NOMBRE VARCHAR2(25),
DIRECCION VARCHAR2(20),
TELEFONO NUMBER(10),
WEB VARCHAR2(25)
);

CREATE TABLE PRODUCTO 
(
ID_PRODUCTO VARCHAR2(20),
NOMBRE VARCHAR2(25),
PRECIO VARCHAR2(5),
STOCK VARCHAR2(10),
ID_CATEGORIA VARCHAR2(10),
ID_PROVEEDOR VARCHAR2(10)
);

CREATE TABLE TELEFONO 
(
NUMERO VARCHAR2(10)
);

CREATE TABLE VENTA 
(
ID_VENTA VARCHAR2(10),
MONTO_TOTAL VARCHAR2(10),
COD_CLIENTE VARCHAR2(15)
);

CREATE TABLE CLIENTE 
(
COD_CLIENTE VARCHAR2(10),
NOMBRE VARCHAR2(25),
CALLE VARCHAR2(20),
NUMERO VARCHAR2(10),
COMUNA VARCHAR2(10),
CIUDAD VARCHAR2(10)
);

CREATE TABLE INCLUYE 
(
ID_VENTA VARCHAR2(15),
ID_PRODUCTO VARCHAR2(10),
CANTIDAD VARCHAR2(10),
PRECIO_VENTA VARCHAR2(10)
);

CREATE TABLE ASOCIADO 
(
COD_CLIENTE VARCHAR2(10),
NUM_TELEFONO VARCHAR2(10)
);


ALTER TABLE CATEGORIA ADD CONSTRAINT  PK_CATEGORIA PRIMARY KEY(ID_CATEGORIA);

ALTER TABLE PROVEEDOR ADD CONSTRAINT  PK_PROVEEDOR PRIMARY KEY(COD_PROVEEDOR);

ALTER TABLE PRODUCTO ADD CONSTRAINT  PK_PRODUCTO PRIMARY KEY(ID_PRODUCTO);
ALTER TABLE PRODUCTO ADD CONSTRAINT FK1_PRODUCTO FOREIGN KEY(ID_CATEGORIA) REFERENCES CATEGORIA(ID_CATEGORIA);
ALTER TABLE PRODUCTO ADD CONSTRAINT FK2_PRODUCTO FOREIGN KEY(ID_PROVEEDOR) REFERENCES PROVEEDOR(COD_PROVEEDOR); 

ALTER TABLE TELEFONO ADD CONSTRAINT  PK_TELEFONO PRIMARY KEY(NUMERO);

ALTER TABLE CLIENTE ADD CONSTRAINT  PK_CLIENTE PRIMARY KEY(COD_CLIENTE);

ALTER TABLE VENTA ADD CONSTRAINT  PK_VENTA PRIMARY KEY(ID_VENTA);
ALTER TABLE VENTA ADD CONSTRAINT  FK1_VENTA FOREIGN KEY(COD_CLIENTE) REFERENCES CLIENTE(COD_CLIENTE);



ALTER TABLE INCLUYE ADD CONSTRAINT  PK_INCLUYE PRIMARY KEY(ID_VENTA,ID_PRODUCTO);
ALTER TABLE INCLUYE ADD CONSTRAINT  FK1_INCLUYE FOREIGN KEY(ID_VENTA) REFERENCES VENTA(ID_VENTA);
ALTER TABLE INCLUYE ADD CONSTRAINT  FK2_INCLUYE FOREIGN KEY(ID_PRODUCTO) REFERENCES PRODUCTO(ID_PRODUCTO);

ALTER TABLE ASOCIADO ADD CONSTRAINT  PK_ASOCIADO PRIMARY KEY(COD_CLIENTE,NUM_TELEFONO);
ALTER TABLE ASOCIADO ADD CONSTRAINT  FK1_ASOCIADO FOREIGN KEY(COD_CLIENTE) REFERENCES CLIENTE(COD_CLIENTE);
ALTER TABLE ASOCIADO ADD CONSTRAINT  FK2_ASOCIADO FOREIGN KEY(NUM_TELEFONO) REFERENCES TELEFONO(NUMERO);




























































