CREATE TABLE REGION 
(
CODREGION VARCHAR(30),
NOMBRE VARCHAR2(30),
CONSTRAINT PK_REGION PRIMARY KEY(CODREGION)
);

CREATE TABLE PROVINCIA
(
CODPROVINCIA VARCHAR2(20),
NOMBRE VARCHAR2(30),
CODREGION VARCHAR2(20),
CONSTRAINT PK_PROVINCIA PRIMARY KEY(CODPROVINCIA),
CONSTRAINT FK1_PROVINCIA FOREIGN KEY(CODREGION) REFERENCES REGION(CODREGION)
);

CREATE TABLE LOCALIDAD
(
CODLOCALIDAD VARCHAR2(20),
NOMBRE VARCHAR2(20),
CODPROVINCIA VARCHAR(20),
CONSTRAINT PK_LOCALIDA PRIMARY KEY(CODLOCALIDAD),
CONSTRAINT FK1_LOCALIDAD FOREIGN KEY(CODPROVINCIA) REFERENCES PROVINCIA(CODPROVINCIA)
);


CREATE TABLE EMPLEADO
(
ID VARCHAR(25),
DNI VARCHAR2(10) UNIQUE,
NOMBRE VARCHAR2(25),
FECHANAC VARCHAR2(10),
TELEFONO VARCHAR2(10),
SALARIO VARCHAR2(20),
CODLOCALIDAD VARCHAR2(20),
CONSTRAINT PK_EMPLEADO PRIMARY KEY(ID),
CONSTRAINT FK1_EMPLEADO FOREIGN KEY(CODLOCALIDAD) REFERENCES LOCALIDAD(CODLOCALIDAD)
);